apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  ports:
  - port: {{ .Values.redis_stack.redis_server_port }}
    name: "{{ .Values.name }}"
    targetPort: {{ .Values.redis_stack.redis_server_port }}
  - port: {{ .Values.redis_stack.redis_insight_port }}
    name: "{{.Values.redis_stack.redis_insight }}"
    targetPort: {{ .Values.redis_stack.redis_insight_port }}
  type: NodePort
  selector:
    app: "{{ .Values.name }}"
