name: redis-stack-server
redis_stack_server:
  image: "redis/redis-stack-server"
  tag: "7.4.0-v8"
  port: 6379
  replicas: 1
  storage_class: standard
  storage: 1Gi
  affinity: {}
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
