name: redis-stack-server
redis_stack_server:
  image: "redis/redis-stack-server"
  tag: "7.4.0-v6"
  port: 6379
  replicas: 1
  storage_class: standard
  storage: 1Gi
  affinity: {}
ingress:
  enabled: true
  name: redis-stack-server-ingress
  className: alb
  annotations: {}
  tls: []
  hosts:
    - host: redis-ss.onemedtest.com
      paths:
        - path: /
          pathType: Prefix
  serviceName: redis-stack-server
  servicePort: 6379
