name: redis-stack-server
redis_stack_server:
  image: "redis/redis-stack-server"
  tag: "7.2.0-v6"
  port: 6379
  serviceType: ClusterIP
  replicas: 1
  storage_class: default
  storage: 1Gi
  env:
  - name: REDIS_ARGS
    valueFrom:
      secretKeyRef:
        name: redis-stack-server
        key: redis-args
  resources:
    limits:
      cpu: 1
      memory: 4G
    requests:
      cpu: 1
      memory: 4G
  nodeSelector:
    type: app
  tolerations:
  - effect: NoSchedule
    key: NodeType
    operator: Equal
    value: app